# Generated by Django 3.2 on 2022-04-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220408_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='rating'),
        ),
        migrations.AddConstraint(
            model_name='filmwork',
            constraint=models.Index(fields=['creation_date'], name='film_work_creation_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='filmwork',
            constraint=models.Index(fields=['title'], name='film_work_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'genre_id'), name='unique_film_work_genre_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.Index(fields=['full_name'], name='person_full_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'person_id', 'role'), name='unique_film_work_person_role_idx'),
        ),
    ]
